{{- if .Values.sentry.ingestConsumerTransactions.autoscaling.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "sentry.fullname" . }}-sentry-ingest-consumer-transactions
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "sentry.fullname" . }}-ingest-consumer
  minReplicas: {{ .Values.sentry.ingestConsumerTransactions.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.sentry.ingestConsumerTransactions.autoscaling.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.sentry.ingestConsumerTransactions.autoscaling.targetCPUUtilizationPercentage }}
{{- end }}
